### ISSUE TITLE
create Authentication template does not support "OTP" enumeration

### ISSUE THREAD

**Issue by soda-universe** [messagebird/java-rest-api#238] opened 2023-06-12 11:28 UTC
Creating an OTP template interface. The java sdk 6.0.0 currently does not support the enumeration of 'OTP'. We are already developing and adapting changes to this interface. Can we arrange for an upgrade?
https://developers.messagebird.com/quickstarts/whatsapp/authentication-templates/
https://github.com/messagebird/java-rest-api/blob/master/api/src/main/java/com/messagebird/objects/integrations/HSMComponentButtonType.java

**Comment by DckcDan** [comment] 2023-06-13 16:02
Thanks for bringing this to our attention. I will work on getting this updated.

**Comment by denizkilic** [comment] 2023-06-15 11:33
Hi @soda-universe 
The issue is resolved in the latest release [v6.1.0](https://github.com/messagebird/java-rest-api/releases/tag/v6.1.0)
Please feel free to reach out if you have any other issues.

**Closed** 2023-06-15 11:35 UTC
