### ISSUE TITLE
Unable to set header_url when creating a template with a HEADER component and format of VIDEO

### ISSUE THREAD

**Issue by hgbrown** [messagebird/java-rest-api#256] opened 2024-05-06 09:09 UTC
When creating a template with a `HEADER` component and a format of `VIDEO`, you cannot set a `header_url` in the example due to the following validation in `HSMComponent.java`:`168-174`:

```java
private void checkHeaderUrl() throws IllegalArgumentException {
    if (!(type.equals(HSMComponentType.HEADER)
        && format.equals(HSMComponentFormat.IMAGE))
    ) {
      throw new IllegalArgumentException("\"header_url\" is available for only HEADER type and IMAGE format.");
    }
  }
```

However, you can send an HTTP request with these values which will succeed:

```json
    {
      "type": "HEADER",
      "format": "VIDEO",
      "example": {
        "header_url": [
          "https://gvipublic.s3.af-south-1.amazonaws.com/ZZZ022/delivery+design.mp4"
        ]
      }
```

**Comment by denizkilic** [comment] 2024-05-28 11:41
Hi @hgbrown 
The issue is resolved by the latest release. ([v6.1.7](https://github.com/messagebird/java-rest-api/releases/tag/v6.1.7))
Please let us know if you need any further assistance.

**Closed by denizkilic** 2024-05-28 11:41 UTC
