### ISSUE TITLE
InvalidFormatException on date string in response from API

### ISSUE THREAD

**Issue by rmacqueen** [messagebird/java-rest-api#119] opened 2020-08-12 15:18 UTC
I'm seeing the following error when calling `startConversation` on the message bird client. The whatsapp message does go through but it looks like the JSON response from message bird API might have changed and is now not getting parsed correctly by this Java library.

```
com.messagebird.exceptions.GeneralException: com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `java.util.Date` from String "2020-08-12T11:21:54.265235776Z": not a valid representation (error: Failed to parse Date value '2020-08-12T11:21:54.265235776Z': Unparseable date: "2020-08-12T11:21:54.265235776Z")
```

**Comment by denizkilic** [comment] 2020-08-13 19:09
Hi @rmacqueen,
Thanks for reporting this issue. The problem is fixed in Release 3.0.15. We are ready to welcoming more issues if you have.

**Closed by denizkilic** 2020-08-13 19:09 UTC
